import { Center, Container, Paper, Stack, Text, Title, createStyles, rem } from "@mantine/core";
import { Helmet } from "react-helmet-async";

const useStyles = createStyles((theme) => ({
  separator: {
    backgroundColor: theme.fn.primaryColor(),
    width: rem(80),
    height: rem(2),
  },
}));

export function TermsOfService() {
  const { classes } = useStyles();

  return (
    <>
      <Helmet>
        <title>Cauli - Terms of Service</title>
        <link rel="canonical" href="https://cauli.projectzucchini.com/terms-of-service" />
      </Helmet>
      <Container size="lg">
        <Paper radius="lg" p="sm">
          <Stack>
            <Title align="center">Terms of Service</Title>
            <Center>
              <div className={classes.separator} />
            </Center>
            <Center>
              <Text italic size="sm">
                Last Updated: May 30, 2023
              </Text>
            </Center>

            <Text>
              These Terms of Service (&quot;Terms&quot;) govern your use of Cauli and its
              integration with external services. By accessing or using Cauli, you agree to these
              Terms. If you do not agree with any part of these Terms, you must not use Cauli.
            </Text>

            <Title order={3}>1) Scope of Service</Title>
            <Text>
              Cauli&apos;s features may be updated or modified from time to time at our sole
              discretion, and we may suspend or terminate the service at any time.
            </Text>

            <Title order={3}>2) Account Registration</Title>
            <Text>
              To use Cauli, you must have a valid Slack account and grant Cauli the necessary
              permissions to integrate with your Slack workspace. You will also need to provide your
              OpenAI API key and Organization ID.
            </Text>

            <Title order={3}>3) Fees for Service</Title>
            <Text>
              There are no fees to use the service. To use Cauli, you must provide information for
              interacting with the OpenAI APIs on your behalf. There may be OpenAI fees. See
              OpenAI&apos;s{" "}
              <a href="https://openai.com/pricing" target="_blank" rel="noreferrer">
                Pricing
              </a>{" "}
              page. Images are generated at the{" "}
              <Text component="span" fw={700}>
                256x256{" "}
              </Text>{" "}
              resolution.
            </Text>

            <Title order={3}>4) User Obligations</Title>
            <Text>
              You agree to use Cauli in compliance with all applicable laws and regulations. You are
              solely responsible for the content you post or share using Cauli. You shall not use
              Cauli for any unlawful, infringing, offensive, or harmful purposes. You agree not to
              abuse or disrupt the functionality of Cauli or interfere with the experience of other
              users.
            </Text>

            <Title order={3}>5) Intellectual Property</Title>
            <Text>
              Cauli, including all associated intellectual property rights, is owned by Project
              Zucchini or its licensors. You agree not to reproduce, modify, distribute, or create
              derivative works based on Cauli without our prior written consent. Any feedback,
              suggestions, or ideas you provide regarding Cauli may be used by us without any
              obligation to compensate you.
            </Text>
            <Text>
              Any images generated by the OpenAI APIs are bound by their{" "}
              <a
                href="https://labs.openai.com/policies/content-policy"
                target="_blank"
                rel="noreferrer"
              >
                Content Policy
              </a>{" "}
              and{" "}
              <a href="https://openai.com/policies/terms-of-use" target="_blank" rel="noreferrer">
                Terms of Use
              </a>
              . Project Zucchini makes no claims to any ownership of the images generated by Cauli.
            </Text>

            <Title order={3}>6) Limitation of Liability</Title>
            <Text>
              To the extent permitted by applicable law, in no event shall Project Zucchini, its
              officers, directors, employees, or affiliates be liable for any direct, indirect,
              incidental, special, or consequential damages arising out of or in connection with
              your use of Cauli. You acknowledge that the use of Cauli is at your own risk.
            </Text>

            <Title order={3}>7) Modifications to the Terms</Title>
            <Text>
              We reserve the right to modify or update these Terms at any time. Any changes will be
              effective immediately upon posting the revised Terms on our website or notifying you.
              Your continued use of Cauli after the effective date of the revised Terms constitutes
              your acceptance of the updated Terms.
            </Text>

            <Title order={3}>8) Termination</Title>
            <Text>
              We may, in our sole discretion, suspend or terminate your access to Cauli without
              prior notice if we believe you have violated these Terms or engaged in any
              unauthorized or illegal activities. Upon termination, your rights to use Cauli will
              immediately cease, and any data associated with your account may be deleted.
            </Text>

            <Title order={3}>9) Governing Law and Jurisdiction</Title>
            <Text>
              These Terms shall be governed by and construed in accordance with the laws of Ontario.
              Any disputes arising out of or in connection with these Terms shall be subject to the
              exclusive jurisdiction of the courts of Ontario.
            </Text>

            <Text>
              Please review these Terms carefully. If you have any questions or concerns regarding
              these Terms, please contact us at{" "}
              <a href="mailto:support@projectzucchini.com" target="_blank" rel="noreferrer">
                support@projectzucchini.com
              </a>
              .
            </Text>
          </Stack>
        </Paper>
      </Container>
    </>
  );
}
